import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Blink Stock Module - DEMO",
  description: "Generated by Nadd.. && Rayy Demo",
  icons: {
    icon: [
      {
        media: '(prefers-color-scheme: light)',
        url: '/favicons/favicon-32x32.png',
      },
      {
        media: '(prefers-color-scheme: dark)',
        url: '/favicons/favicon-32x32.png',
      },
    ],
    apple: '/favicons/apple-touch-icon.png',
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
